version: "3.5"
services:
  frontend:
    container_name: template-dashboard
    build: ./dashboard
    ports:
      - "8501:8501"
    volumes:
       - ./dashboard:/app
    env_file:
      - ./dashboard/.env
    restart: always
